version: "3.9"

services:

  #  redis:
  #    image: redis
  #    ports:
  #      - "6379:6379"

  db:
    image: postgres:15.0
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=diplom_user
      - POSTGRES_PASSWORD=diplom_pswd
      - POSTGRES_DB=diplom_db