# API-запросы для покупателей магазина

@baseUrl = http://127.0.0.1:8000

###

# Список магазинов (Successfully: HTTP/1.1 200 OK)
GET {{baseUrl}}/shops
Content-Type: application/json


###

# Список товаров (Successfully: HTTP/1.1 200 OK)
GET {{baseUrl}}/api/v1/products
Content-Type: application/json


###

# Фильтрация товаров (Successfully: HTTP/1.1 200 OK)
GET {{baseUrl}}/api/v1/products?shop_id=1&category_id=2
Content-Type: application/json


###

# Категории товаров (Successfully: HTTP/1.1 200 OK)
GET {{baseUrl}}/api/v1/categories
Content-Type: application/json


###

# Добавить товары в корзину (Successfully: HTTP/1.1 200 OK)
POST {{baseUrl}}/api/v1/basket
Content-Type: application/json
Authorization: Token a0d9699a2e09ee9b6ecb87fb805e47d7f12ee0f8

{
    "items":[
        {"product_info": 1, "quantity": 2},
        {"product_info": 2, "quantity": 3}
    ]
}

# {
#   "Status": true,
#   "Создано объектов": 2
# }


###

# Редакиторование количества товаров в корзине (Successfully: HTTP/1.1 200 OK)
PUT {{baseUrl}}/api/v1/basket
Content-Type: application/json
Authorization: Token c3e06221b0e0beba461926b4b2a5a77499a2ebf0

{
    "items":[
        {
            "id": 1,
            "quantity": 10
        }
    ]
}

# {
#   "Status": true,
#   "Обновлено объектов": 1
# }


###

# Удаление товара из корзины (Successfully: HTTP/1.1 200 OK)
DELETE {{baseUrl}}/api/v1/basket
Content-Type: application/json
Authorization: Token c3e06221b0e0beba461926b4b2a5a77499a2ebf0

{
    "items": "2"
}

# {
#   "Status": true,
#   "Удалено объектов": 1
# }


###

# Получение корзины (Successfully: HTTP/1.1 200 OK)
GET {{baseUrl}}/api/v1/basket
Content-Type: application/json
Authorization: Token c3e06221b0e0beba461926b4b2a5a77499a2ebf0


###

# Размещение заказа (Successfully: HTTP/1.1 200 OK)
POST {{baseUrl}}/api/v1/order
Content-Type: application/json
Authorization: Token c3e06221b0e0beba461926b4b2a5a77499a2ebf0

{
    "id": "1"
    # "contact": "2"
}

###

# Получение заказов (Successfully: HTTP/1.1 200 OK)
GET {{baseUrl}}/api/v1/order
Content-Type: application/json
Authorization: Token c3e06221b0e0beba461926b4b2a5a77499a2ebf0

###
