# API-запросы для Поставщиков

@baseUrl = http://127.0.0.1:8000/


###

# Получить статус партнера
GET {{baseUrl}}/api/v1/partner/state
Content-Type: application/json
Authorization: Token 06ee639c399d21e54d7af52d13a39e46f5221dfd


###

# Обновления статуса партнера
PATCH {{baseUrl}}/partner/state
Content-Type: application/json
Authorization: Token 06ee639c399d21e54d7af52d13a39e46f5221dfd

{
    "state": "on"
}

###

# Получения заказов магазина (Successfully - HTTP/1.1 200 OK)
GET {{baseUrl}}/partner/orders
Content-Type: application/json
Authorization: Token 2a1335f70806544d2b14cc3154199deab0510dec

###

# Обновление прайса (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/api/v1/partner/update
Content-Type: application/json
Authorization: Token 06ee639c399d21e54d7af52d13a39e46f5221dfd

{
    "url": "https://raw.githubusercontent.com/matolgithub/python-final-diplom/master/netology/data/shop1.yaml"
}

# {
#   "Status": true,
#   "Sent_email_status": "Sent"
# }

###

