# API-запросы для Поставщиков

@baseUrl = http://127.0.0.1:8000/api/v1


###

# Получить статус партнера
GET {{baseUrl}}/partner/state
Content-Type: application/json
Authorization: Token 128b897d8740d088e54dab5e696f9f3276658385


###

# Обновления статуса партнера
POST {{baseUrl}}/partner/state
Content-Type: application/json
Authorization: Token 128b897d8740d088e54dab5e696f9f3276658385

{
    "state": "on"
}

# {
#   "Status": true
# }

###

# Получения заказов магазина (Successfully - HTTP/1.1 200 OK)
GET {{baseUrl}}/partner/orders
Content-Type: application/json
Authorization: Token 128b897d8740d088e54dab5e696f9f3276658385

###

# Обновление прайса (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/partner/update
Content-Type: application/json
Authorization: Token 128b897d8740d088e54dab5e696f9f3276658385

{
    "url": "https://raw.githubusercontent.com/matolgithub/python-final-diplom/master/netology/data/shop1.yaml"
}

# {
#   "Status": true,
#   "Sent_email_status": "Sent"
# }

###

# Обновление прайса через Celery tasks (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/partner/update_celery
Content-Type: application/json
Authorization: Token 128b897d8740d088e54dab5e696f9f3276658385

{
    "url": "https://github.com/matolgithub/python-final-diplom/tree/master/orders/orders/yaml/goods.yaml"
}

# {
#   "Status": true,
#   "Sent_email_status": "Sent_With_Celery"
# }

###

