# API-запросы для Пользователей сервиса

@baseUrl = http://127.0.0.1:8000/api/v1


###

# Создание пользователя (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/user/register
Content-Type: application/json

{
    "first_name": "first_name_1",
    "last_name": "last_name_1",
    "email": "matolpydev@gmail.com",
    "password":"dkvdk545nkdsn",
    "company":"company_1",
    "position":"sales_manager",
    "type": "buyer",
    "is_staff": true
}

# {
#   "Status": true
# }

###


# Попытка создания пользователя с уже существующий в базе эл.почтой (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/user/register
Content-Type: application/json

{
    "first_name": "first_name_10",
    "last_name": "last_name_10",
    "email": "matolpydev@gmail.com",
    "password":"54trtrdkvdk545nkdsn",
    "company":"company_10",
    "position":"sales_manager",
    "type": "shop"
}

# {
#   "Status": false,
#   "Errors": {
#     "email": [
#       "User with this email address already exists."
#     ]
#   }
# }

###

# Создание пользователя (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/user/register
Content-Type: application/json

{
    "first_name": "first_name_2",
    "last_name": "last_name_2",
    "email": "111222333@gmail.com",
    "password":"fnvjdnk454j5nkn",
    "company":"company_2",
    "position":"director",
    "type": "shop"
}

###

# Создание пользователя (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/user/register
Content-Type: application/json

{
    "username": "admin",
    "first_name": "first_name_3",
    "last_name": "last_name_3",
    "email": "89175955650@mail.ru",
    "password":"fdjdfdjb242ksskzx",
    "company":"company_3",
    "position":"top_manager",
    "type": "buyer"
}

###

# Подтверждение емаил (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/user/register/confirm
Content-Type: application/json

{
    "email": "matolpydev@gmail.com",
    "token": "c3e06221b0e0beba461926b4b2a5a77499a2ebf0"
}

###

# Авторизация пользователя (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/user/login
Content-Type: application/json

{
    "email": "matolpydev@gmail.com",
    "password":"dkvdk545nkdsn"
}

# {
#   "Status": true,
#   "Token": "c3e06221b0e0beba461926b4b2a5a77499a2ebf0"
# }

###

# Получение контактов (Successfully - HTTP/1.1 200 OK)
GET {{baseUrl}}/user/contact
Content-Type: application/json
Authorization: Token 00c98148d6857dc285d0e7290c7afd57c858b027


###

# Добавление контакта
POST {{baseUrl}}/user/contact
Content-Type: application/json
Authorization: Token 00c98148d6857dc285d0e7290c7afd57c858b027

{
    "city": "city_1",
    "street": "street_1",
    "phone": "+79999999999"
}

###

# Редактирования контакта (Successfully - HTTP/1.1 200 OK)
PUT {{baseUrl}}/user/contact
Content-Type: application/json
Authorization: Token 3a35918691014370883e7b5716e0a119b4908b87

{
    "id": 1,
    "city": "city_1",
    "street": "street_11",
    "phone": "+7988888888888"
}

###

# Удаление контакта (Successfully - HTTP/1.1 200 OK)
DELETE {{baseUrl}}/user/contact
Content-Type: application/json
Authorization: Token 892afaa2832163077e3bcb0a621a963c2e212d88

{
    "items": "1"
}


###

# Редактирования пользователя (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/user/details
Content-Type: application/json
Authorization: Token 892afaa2832163077e3bcb0a621a963c2e212d88

{
    "email": "matolpydev@gmail.com"
}

# {
#   "Status": true
# }

###

# Редактирования пользователя (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/user/details
Content-Type: application/json
Authorization: Token 892afaa2832163077e3bcb0a621a963c2e212d88

{
    "type": "shop"
}

# {
#   "Status": true
# }

###


# Получение информации о пользователе 
GET {{baseUrl}}/user/details
Content-Type: application/json
Authorization: Token 892afaa2832163077e3bcb0a621a963c2e212d88

# {
#   "id": 1,
#   "first_name": "first_name_1",
#   "last_name": "last_name_1",
#   "email": "matolpydev@gmail.com",
#   "company": "company_1",
#   "position": "sales_manager",
#   "contacts": []
# }


###

# Сброс пароля пользователя (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/user/password_reset
Content-Type: application/json

{
"email": "matolpydev@gmail.com"
}

# {
#   "status": "OK"
# }


###

# Подтверждения нового пароля пользователя (Successfully - HTTP/1.1 200 OK)
POST {{baseUrl}}/user/password_reset
Content-Type: application/json

{
"email": "matolpydev@gmail.com",
"password": "new_password",
"token": "892afaa2832163077e3bcb0a621a963c2e212d88"
}

# {
#   "status": "OK"
# }

###
