# Generated by Django 2.2.13 on 2022-12-16 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0002_auto_20221216_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_service.Contact', verbose_name='Контакт покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата-время заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('visit', 'Пассивный статус'), ('basket', 'Статус корзины'), ('new', 'Новый'), ('confirmed', 'Подтвержден'), ('assembled', 'Собран'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='visit', max_length=15, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь - покупатель'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название параметра'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='model',
            field=models.CharField(blank=True, max_length=60, verbose_name='Модель продукта'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price_rrc',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Рекомендуемая розничная цена'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество продукта'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение параметра'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Статус получения заказов'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь - покупатель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('shop', 'Магазин'), ('buyer', 'Покупатель'), ('none_type', 'Посетитель')], default='none_type', max_length=5, verbose_name='Тип пользователя'),
        ),
    ]
