# Generated by Django 3.2.16 on 2022-12-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0003_alter_category_id_alter_confirmemailtoken_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
    ]
