# Generated by Django 3.2.16 on 2022-12-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0004_shop_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('none_state', 'Без статуса'), ('basket', 'Статус заказа - Корзина'), ('new', 'Статус заказа - Новый'), ('confirmed', 'Статус заказа -Подтвержден'), ('collected', 'Статус заказа - Собран'), ('sent', 'Статус заказа - Отправлен'), ('delivered', 'Статус заказа - Доставлен'), ('canceled', 'Статус заказа - Отменен')], max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('visitor', 'Посетитель сервиса'), ('shop', 'Магазин'), ('buyer', 'Покупатель')], default='buyer', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
